Repository chroma-core/chroma, pull requests merged in 2023-11, with the labels that each got.

#1314 js_release_alpha/1.5.12
  bin/integration-test
  clients/js/README.md
  clients/js/package-lock.json
  clients/js/package.json
  clients/js/src/embeddings/CohereEmbeddingFunction.ts
  clients/js/src/embeddings/OpenAIEmbeddingFunction.ts
  clients/js/src/embeddings/TransformersEmbeddingFunction.ts
  clients/js/src/embeddings/WebAIEmbeddingFunction.ts
  clients/js/src/index.ts
  clients/js/src/utils.ts
  clients/js/tsconfig.json
  clients/js/tsconfig.module.json
  clients/js/tsup.config.ts
  clients/js/yarn.lock
  yarn.lock
Labels: release

#1337 1.6.1 commit for JS release
  clients/js/package.json
Labels: release

#1351 [RELEASE] 0.4.16
  chromadb/__init__.py
Labels: breaking change, release

#1381 [RELEASE] 0.4.17
  chromadb/__init__.py
Labels: release

#1415 Release 0.4.18
  chromadb/__init__.py
Labels: release

#1371 [ENH]: Embedding Function - Hugging Face Text Embedding Server
  chromadb/utils/embedding_functions.py
  clients/js/src/embeddings/HuggingFaceEmbeddingServerFunction.ts
  clients/js/src/index.ts
  examples/server_side_embeddings/huggingface/docker-compose.yml
  examples/server_side_embeddings/huggingface/test.ipynb
Labels: taz-sprint-1

#1279 [ENH]: Local Observability Stack with OTEL and Zipkin
  examples/observability/README.md
  examples/observability/docker-compose.local-observability.yml
  examples/observability/otel-collector-config.yaml
Labels: taz-sprint-1
