Repository chroma-core/chroma, pull requests merged in 2023-05, with the labels that each got.

#479 Upgrade to 0.3.22
  chromadb/__init__.py
Labels: release

#331 Adds device (cuda) option for TransformerEmbeddingFunction
  chromadb/utils/embedding_functions.py
Labels: approved

#382 Add ability to pass model name to CohereEmbeddingFunction
  clients/js/src/index.ts
Labels: approved

#307 added missing embedding_function param in get_or_create_collection
  chromadb/api/__init__.py
  chromadb/api/types.py
  chromadb/test/test_api.py
Labels: approved

#444 Add Python 3.10.0 note to DEVELOP.md
  DEVELOP.md
Labels: approved

#321 Add example demonstrating using openai & cohere embeddings
  examples/alternative_embeddings.ipynb
Labels: approved

#575 Return 0 results Instead of raising NoDatapointException on an empty filter
  chromadb/api/local.py
  chromadb/db/clickhouse.py
  chromadb/db/index/hnswlib.py
  chromadb/errors.py
  chromadb/test/property/test_filtering.py
  chromadb/test/test_api.py
Labels: breaking change

#267 Switch to ONNX model for default embedding model
  chromadb/api/models/Collection.py
  chromadb/test/test_api.py
  chromadb/utils/embedding_functions.py
  pyproject.toml
  requirements.txt
Labels: approved

#608 Release 0.3.24
  chromadb/__init__.py
Labels: release

#607 bump JS to 1.5.0
  clients/js/package.json
Labels: breaking change, release

#610 Add a thin client
  .github/workflows/chroma-client-integration-test.yml
  .github/workflows/chroma-release-python-client.yml
  chromadb/api/__init__.py
  chromadb/api/fastapi.py
  chromadb/api/local.py
  chromadb/api/models/Collection.py
  chromadb/config.py
  chromadb/test/test_api.py
  chromadb/utils/embedding_functions.py
  clients/python/README.md
  clients/python/build_python_thin_client.sh
  clients/python/integration-test.sh
  clients/python/is_thin_client.py
  clients/python/pyproject.toml
  docker-compose.test.yml
Labels: breaking change
