Repository chroma-core/chroma, pull requests merged in 2023-12, with the labels that each got.

#1119 [ENH]: Docker compose data volume
  docker-compose.server.example.yml
  docker-compose.test-auth.yml
  docker-compose.test.yml
  docker-compose.yml
Labels: taz-sprint-1

#1398 [ENH] add AdminClient to API, add tenancy to JS client
  clients/js/package.json
  clients/js/src/AdminClient.ts
  clients/js/src/ChromaClient.ts
  clients/js/src/Collection.ts
  clients/js/src/generated/api.ts
  clients/js/src/generated/models.ts
  clients/js/src/index.ts
  clients/js/src/types.ts
  clients/js/src/utils.ts
  clients/js/test/admin.test.ts
  clients/js/test/get.collection.test.ts
  clients/js/test/initAdminClient.ts
Labels: ready-to-merge

#1509 Release 0.4.19
  chromadb/__init__.py
Labels: release

#1450 [ENH] Fix for record pagination
  chromadb/segment/impl/metadata/sqlite.py
  chromadb/test/property/test_filtering.py
  chromadb/test/segment/test_metadata.py
  clients/js/src/index.ts
Labels: ready-to-merge

#1451 [ENH] Pagination count collections
  bin/cluster-test.sh
  chromadb/api/__init__.py
  chromadb/api/client.py
  chromadb/api/fastapi.py
  chromadb/api/segment.py
  chromadb/auth/__init__.py
  chromadb/db/__init__.py
  chromadb/db/impl/grpc/client.py
  chromadb/db/mixins/sysdb.py
  chromadb/db/system.py
  chromadb/server/fastapi/__init__.py
  chromadb/test/property/test_collections.py
  clients/js/src/ChromaClient.ts
  clients/js/src/Collection.ts
  clients/js/src/generated/api.ts
  clients/js/src/generated/configuration.ts
  clients/js/src/generated/index.ts
  clients/js/src/generated/models.ts
  clients/js/src/generated/runtime.ts
  clients/js/src/index.ts
  clients/js/src/types.ts
  clients/js/test/auth.basic.test.ts
  clients/js/test/initClient.ts
Labels: ready-to-merge

#1530 [Release] 0.4.20
  chromadb/__init__.py
Labels: release

#1533 release JS to 1.7.1
  clients/js/package.json
Labels: release

#1550 1.7.3
  clients/js/package.json
Labels: release

#1559 Release 0.4.21
  chromadb/__init__.py
Labels: release
