Repository chroma-core/chroma, pull requests merged in 2023-07, with the labels that each got.

#784 Release 0.3.27
  chromadb/__init__.py
Labels: release

#800 0.3.28
  chromadb/__init__.py
Labels: release

#715 add header and direct url support
  chromadb/api/fastapi.py
  chromadb/config.py
  chromadb/test/test_chroma.py
Labels: question

#829 Release 0.4.0
  chromadb/__init__.py
Labels: release

#852 Release 0.4.2
  chromadb/__init__.py
Labels: release

#738 update dockerfile to include a version of gcc that supports C++11
  Dockerfile
Labels: question

#902 remove raw_sql and pandas
  chromadb/api/__init__.py
  chromadb/api/fastapi.py
  chromadb/api/segment.py
  chromadb/db/__init__.py
  chromadb/server/fastapi/__init__.py
  chromadb/server/fastapi/types.py
  clients/python/pyproject.toml
  pyproject.toml
  requirements.txt
Labels: breaking change

#903 remove create_index which we dont use
  chromadb/api/__init__.py
  chromadb/api/fastapi.py
  chromadb/api/models/Collection.py
  chromadb/api/segment.py
  chromadb/db/__init__.py
  chromadb/server/fastapi/__init__.py
  chromadb/test/test_api.py
Labels: breaking change

#906 remove increment index
  chromadb/api/__init__.py
  chromadb/api/fastapi.py
  chromadb/api/models/Collection.py
  chromadb/api/segment.py
  chromadb/db/__init__.py
  chromadb/server/fastapi/__init__.py
  chromadb/server/fastapi/types.py
  chromadb/test/test_api.py
Labels: breaking change

#916 Release 0.4.4
  chromadb/__init__.py
Labels: release
