Repository chroma-core/chroma, pull requests merged in 2024-09, with the labels that each got.

#2233 [DOC] Update JS client documentation
  docs/docs.trychroma.com/pages/deployment/auth.md
Labels: community

#2629 [DOC]: use `pnpm add <pkg>` instead of `pnpm install <pkg>`
  docs/docs.trychroma.com/pages/getting-started.md
Labels: blocked, community

#2550 [DOC] Update the add function in the guide, which is currently using the old version with text instead of documents.
  docs/docs.trychroma.com/pages/guides/multimodal.md
Labels: blocked, community

#2509 [CHORE] DeprecationWarning in httpx\_content.py:202:
  chromadb/api/async_fastapi.py
  chromadb/api/fastapi.py
Labels: community

#2771 [DOC]: Update Langchain integration example and fix broken link
  docs/docs.trychroma.com/pages/integrations/langchain.md
Labels: community

#2566 [DOC]: Yarn package install in getting-started.md
  docs/docs.trychroma.com/pages/getting-started.md
Labels: documentation, community

#2817 [RELEASE] 0.5.6
  chromadb/__init__.py
Labels: release

#2862 [RELEASE] 0.5.10
  chromadb/__init__.py
  docs/docs.trychroma.com/pages/deployment/migration.md
Labels: release

#2869 [RELEASE] 0.5.11
  chromadb/__init__.py
  docs/docs.trychroma.com/pages/deployment/migration.md
Labels: release
