Repository chroma-core/chroma, pull requests merged in 2024-10, with the labels that each got.

#2913 [RELEASE] 0.5.12
  chromadb/__init__.py
  docs/docs.trychroma.com/pages/deployment/migration.md
Labels: release

#2924 [BUG]: Lint job - python setup failure
  .github/workflows/pr.yml
Labels: ready-to-merge

#1977 [ENH]: OpenAI embedding dimensions
  chromadb/test/ef/test_openai_ef.py
  chromadb/utils/embedding_functions/openai_embedding_function.py
  clients/js/src/embeddings/OpenAIEmbeddingFunction.ts
  clients/js/test/add.collections.test.ts
Labels: EF

#2959 [RELEASE] 0.5.15
  chromadb/__init__.py
Labels: release

#3015 [RELEASE] 0.5.16
  .github/workflows/release-chromadb.yml
  chromadb/__init__.py
  deployments/gcp/chroma.tfvars
  deployments/gcp/main.tf
Labels: release

#3036 [RELEASE] 0.5.17
  chromadb/__init__.py
  deployments/aws/chroma.cf.json
  deployments/azure/chroma.tfvars.tf
  deployments/azure/main.tf
  deployments/gcp/chroma.tfvars
  deployments/gcp/main.tf
  docs/docs.trychroma.com/pages/deployment/migration.md
Labels: release
